### ISSUE TITLE
Missing sapling_provider in 1.17 Pre-Release 1

### ISSUE THREAD

**Issue by Cevclass** [misode/misode.github.io#144]
[10:59:10] [Render thread/WARN]: Failed to validate datapack
java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Error loading registry data: No key sapling_provider in MapLike[{"ignore_vines":true,"force_dirt":false,"minimum_size":{"type":"minecraft:two_layers_feature_size","min_clipped_height":4,"limit":0,"lower_size":0,"upper_size":0},"dirt_provider":{"type":"minecraft:simple_state_provider","state":{"Name":"minecraft:dirt"}},"trunk_provider":{"type":"minecraft:simple_state_provider","state":{"Name":"minecraft:birch_log","Properties":{"axis":"y"}}},"foliage_provider":{"type":"minecraft:simple_state_provider","state":{"Name":"minecraft:oak_leaves","Properties":{"persistent":"false","distance":"7"}}},"trunk_placer":{"type":"minecraft:fancy_trunk_placer","base_height":3,"height_rand_a":11,"height_rand_b":0},"foliage_placer":{"type":"minecraft:fancy_foliage_placer","radius":2,"offset":4,"height":4},"decorators":[]}]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) [?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
	at aqu.c(SourceFile:151) [1.17-pre1.jar:?]
	at aqy.c(SourceFile:23) [1.17-pre1.jar:?]
	at aqu.z(SourceFile:125) [1.17-pre1.jar:?]
	at aqu.bq(SourceFile:110) [1.17-pre1.jar:?]
	at dvo.f(SourceFile:1077) [1.17-pre1.jar:?]
	at dvo.e(SourceFile:730) [1.17-pre1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:217) [1.17-pre1.jar:?]

**Comment by misode** [comment]
This was a change in 1.17-pre1. I just updated the generators for this version 🙂
