### ISSUE TITLE
Error when using default continents settings in noise router

### ISSUE THREAD

**Issue by Apollo4O4** [misode/misode.github.io#223]
```
Error: Something went wrong rendering the generator: Missing key in minecraft:worldgen/density_function: minecraft:overworld/continents
    at Ff.getOrThrow (../../node_modules/deepslate/dist/deepslate.esm.js:1:12356)
    at getOrThrow (../../node_modules/deepslate/dist/deepslate.esm.js:1:11830)
    at value (../../node_modules/deepslate/dist/deepslate.esm.js:1:76178)
    at e2 (../../node_modules/deepslate/dist/deepslate.esm.js:1:76456)
    at fromJson (../../node_modules/deepslate/dist/deepslate.esm.js:1:88333)
    at (https://misode.github.io/assets/index.37e720ee.js:1:81167) (src/app/components/previews/BiomeSourcePreview.tsx:12:83)
    at firstOctave (src/app/components/previews/BiomeSourcePreview.tsx:140:13)
    at n2 (../../node_modules/preact/hooks/dist/hooks.module.js:1:825)
    at k.jn (src/app/components/previews/BiomeSourcePreview.tsx:12:26)
    at constructor (../../node_modules/preact/dist/preact.module.js:1:8049)
```

**Comment by misode** [comment]
@Apollo4O4 This issue should now be fixed
