### ISSUE TITLE
SyntaxError: Error importing: Unexpected token a

### ISSUE THREAD

**Issue by LHKNOOB** [misode/misode.github.io#276]
```
SyntaxError: Error importing: Unexpected token a
    at vi (../../node_modules/comment-json/src/parse.js:87:16)
    at Xe (../../node_modules/comment-json/src/parse.js:132:4)
    at Wr (../../node_modules/comment-json/src/parse.js:269:4)
    at bt (../../node_modules/comment-json/src/parse.js:365:11)
    at Module.Zr (../../node_modules/comment-json/src/parse.js:417:15)
    at parse (src/app/services/Source.ts:24:23)
    at async (src/app/services/Source.ts:43:8)
    at async (src/app/components/generator/SourcePanel.tsx:71:17)
```

**Comment by misode** [comment]
Can you please include the text that you tried to import? Most likely the JSON is malformed and this is working as intended.
