### ISSUE TITLE
ReferenceError: caches is not defined

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [misode/misode.github.io#279]
```
ReferenceError: caches is not defined
    at caches (DataFetcher.ts:267:2)
    at patch (DataFetcher.ts:279:9)
    at applyPatches (DataFetcher.ts:33:7)
    at validateCache (DataFetcher.ts:154:7)
    at fn (useAsyncFn.ts:45:9)
    at callback (useAsync.ts:14:2)
    at hook (../../preact/hooks/src/index.js:386:17)
    at Array.forEach (<anonymous>)
    at forEach (../../preact/hooks/src/index.js:314:37)
```

**Comment by misode** [comment]
Duplicate of #275

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
