### ISSUE TITLE
hi I have this error in the loot table generator

### ISSUE THREAD

**Issue by AstraX22** [misode/misode.github.io#299]
```
TypeError: Something went wrong rendering the generator: Something went wrong rendering the generator: Cannot read properties of undefined (reading 'indexOf')
    at indexOf (src/app/components/ItemTooltip.tsx:56:19)
    at fakeTranslation (src/app/components/ItemTooltip.tsx:21:73)
    at en.im (../../node_modules/preact/dist/preact.module.js:1:8150)
    at dd (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
```

**Comment by misode** [comment]
@AstraX22 Do you know what the contents of the loot table JSON were when you got this error? Is there a way to reproduce this?
