### ISSUE TITLE
TypeError: Something went wrong rendering the generator: Cannot read properties of null (reading 'color')

### ISSUE THREAD

**Issue by BZ8BB8** [misode/misode.github.io#312]
* Occurred to me when creating a custom loot table
* Occurs when creating a new array under "Set name" under "Functions" of an entry

## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.19.3`
 * Latest version: `1.19.3`

### Stack trace
```
TypeError: Something went wrong rendering the generator: Cannot read properties of null (reading 'color')
    at color (src/app/components/TextComponent.tsx:80:14)
    at inherit (src/app/components/TextComponent.tsx:54:35)
    at consumer (src/app/components/TextComponent.tsx:58:3)
    at visitComponent (src/app/components/TextComponent.tsx:54:3)
    at visitComponent (src/app/components/TextComponent.tsx:31:2)
    at n (../../node_modules/preact/hooks/dist/hooks.module.js:1:902)
    at useMemo (src/app/components/TextComponent.tsx:29:15)
    at Jn.y8 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at Kl (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
```

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone",
          "functions": [
            {
              "function": "minecraft:set_name",
              "count": 1,
              "name": [
                null,
                {
                  "text": ""
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
Thanks for reporting this issue!
