### ISSUE TITLE
SyntaxError: Error importing: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Danjhop4** [misode/misode.github.io#348]
## Crash report
 * Page url: `https://misode.github.io/dimension/?version=1.19.4`
 * Generator ID: `dimension`
 * Current version: `1.19.4`
 * Latest version: `1.19.4-pre1`

### Stack trace
```
SyntaxError: Error importing: Unexpected end of JSON input
    at yi (../../node_modules/comment-json/src/parse.js:94:16)
    at unexpected_end (../../node_modules/comment-json/src/parse.js:120:4)
    at type (../../node_modules/comment-json/src/parse.js:128:16)
    at is (../../node_modules/comment-json/src/parse.js:246:10)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:283:32)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:417:15)
    at parse (src/app/services/Source.ts:24:23)
    at async (src/app/services/Source.ts:43:8)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:overworld",
  "generator": {
    "type": "minecraft:noise",
    "settings": "minecraft:overworld",
    "biome_source": {
      "type": "minecraft:multi_noise",
      "biomes": [
        {
          "biome": "minecraft:plains",
          "parameters": {
            "temperature": 0,
            "humidity": 0,
            "continentalness": 0,
            "erosion": 0,
            "weirdness": 0,
            "depth": 0,
            "offset": 0
          }
        }
      ]
    }
  }
}
</pre>
</details>

**Comment by Danjhop4** [comment]
was  trying to use th e 1.12 data gen

**Comment by Danjhop4** [comment]
1.20 not 1.12

**Comment by Danjhop4** [comment]
Appears I spliced it at the wrong point
