### ISSUE TITLE
Error: Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:efficiency: 3

### ISSUE THREAD

**Issue by olesyayt** [misode/misode.github.io#353]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.19.3`
 * Latest version: `1.19.4-rc1`

### Stack trace
```
Error: Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:efficiency: 3
    at new (../../node_modules/deepslate/lib/core/Identifier.js:13:18)
    at nr.parse (../../node_modules/deepslate/lib/core/Identifier.js:39:19)
    at parse (src/app/components/previews/LootTable.ts:340:38)
    at Array.forEach (<anonymous>)
    at forEach (src/app/components/previews/LootTable.ts:338:31)
    at item (src/app/components/previews/LootTable.ts:267:44)
    at compositeFunction (src/app/components/previews/LootTable.ts:257:2)
    at entryConsumer (src/app/components/previews/LootTable.ts:232:17)
    at entries (src/app/components/previews/LootTable.ts:164:15)
    at pool (src/app/components/previews/LootTable.ts:122:15)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:chest",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone",
          "functions": [
            {
              "function": "minecraft:set_enchantments",
              "enchantments": {
                "minecraft:efficiency:": 0
              },
              "count": 1
            }
          ]
        }
      ],
      "bonus_rolls": {
        "min": 0,
        "max": 0
      }
    },
    {
      "rolls": {
        "min": 15,
        "max": 19
      },
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:arrow"
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
You have a typo in your loot table. `"minecraft:efficiency:": 0` should be `"minecraft:efficiency": 0` (removing the trailing colon in the key)
