### ISSUE TITLE
SyntaxError: Something went wrong rendering the generator: Expected ',' or ']' after array element in JSON at position 7

### ISSUE THREAD

**Issue by Manasukiyami-Github2** [misode/misode.github.io#372]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.19`
 * Latest version: `23w18a`

### Stack trace
```
SyntaxError: Something went wrong rendering the generator: Expected ',' or ']' after array element in JSON at position 7
    at JSON.parse (<anonymous>)
    at parse (src/app/components/ItemTooltip.tsx:100:115)
    at Array.map (<anonymous>)
    at dn.map (../../node_modules/deepslate/lib/nbt/tags/NbtAbstractList.js:25:26)
    at map (src/app/components/ItemTooltip.tsx:100:70)
    at ur.I8 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at Fc (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
```

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:firework_star",
          "functions": [
            {
              "function": "minecraft:set_nbt",
              "tag": "{display:{Name:'{\"text\":\"Rare Candy\",\"color\":\"aqua\",\"italic\":false}',Lore:['[\"text\":\"[Right-Click to Use]\"]']}}",
              "count": 1
            }
          ]
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
You have an error in your loot table, you're using incorrect square brackets in the Lore part of the NBT:
`Lore:['[\"text\":\"[Right-Click to Use]\"]']`
-> should be `Lore:['{\"text\":\"[Right-Click to Use]\"}']`

However I am fixing this so the site won't completely break.
