### ISSUE TITLE
Error: Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:stonewц

### ISSUE THREAD

**Issue by cbejl** [misode/misode.github.io#376]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.19.4`
 * Latest version: `1.20-pre1`

### Stack trace
```
Error: Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:stonewц
    at rr (../../node_modules/deepslate/lib/core/Identifier.js:13:18)
    at parse (../../node_modules/deepslate/lib/core/Identifier.js:39:19)
    at parse (src/app/components/previews/LootTable.ts:232:42)
    at entries (src/app/components/previews/LootTable.ts:164:15)
    at pool (src/app/components/previews/LootTable.ts:122:15)
    at lootTable (src/app/components/previews/LootTable.ts:43:15)
    at table (src/app/components/previews/LootTablePreview.tsx:27:34)
    at U1 (../../node_modules/preact/hooks/dist/hooks.module.js:1:2451)
    at ve.__r (../../node_modules/preact/hooks/dist/hooks.module.js:1:1644)
    at Q (../../node_modules/preact/compat/dist/compat.module.js:1:7258)
    at A (../../node_modules/preact/dist/preact.module.js:1:5853)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at n (../../node_modules/preact/dist/preact.module.js:1:2131)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at j (../../node_modules/preact/dist/preact.module.js:1:1493)
    at Sa (../../node_modules/preact/dist/preact.module.js:1:1391)

```

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stonewц"
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by cbejl** [comment]
I accidentally wrote a letter in the wrong layout and the half-hour selection of the loot table was reset to zero

**Comment by misode** [comment]
Hi! Apologies in case you lost any data. Thanks for the report, I have now fixed this.
