### ISSUE TITLE
Datapack cannot be verified - Cusomized worlds 1.20

### ISSUE THREAD

**Issue by RhythmicSys** [misode/misode.github.io#390]
Attempting to make a customized world on https://misode.github.io/customized/?tab=basic resulted in a pack that was unable to be verified

<details>
<summary>logs</summary>

```
13:38:13.014
fuu
Render thread
Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
13:38:13.026
fuu
Render thread
Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
13:38:13.027
fuu
Render thread
Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
13:38:13.028
fuu
Render thread
Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
13:38:13.028
fuu
Render thread
Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
13:38:13.155
fki
Render thread
Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
13:38:13.186
fuu
Render thread
[customized.zip](https://github.com/misode/misode.github.io/files/11780046/customized.zip)

Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
13:38:13.187
fuu
Render thread
Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
13:38:13.188
fuu
Render thread
Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
13:38:18.611
cjd
Render thread
Loaded 7 recipes
13:38:18.684
af
Render thread
Loaded 1271 advancements
13:38:31.297
acl
Render thread
Registry loading errors:
> Errors in registry minecraft:worldgen/structure_set:
>> Errors in element minecraft:buried_treasure:
java.lang.IllegalStateException: Failed to parse minecraft:worldgen/structure_set/buried_treasure.json from pack file/customized.zip
	at acl.a(SourceFile:179)
	at acl$b.a(SourceFile:61)
	at acl.a(SourceFile:98)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at acl.a(SourceFile:98)
	at adj.a(SourceFile:67)
	at adj.b(SourceFile:71)
	at adj.a(SourceFile:34)
	at eza.a(SourceFile:600)
	at eza.a(SourceFile:590)
	at eza.a(SourceFile:562)
	at exu.c(SourceFile:56)
	at exv.aw_(SourceFile:77)
	at exv.a(SourceFile:108)
	at epi.c(SourceFile:94)
	at eoz.a(SourceFile:56)
	at epf.a(SourceFile:189)
	at eqs.a(SourceFile:38)
	at eno.b(SourceFile:98)
	at euq.a(SourceFile:409)
	at eno.a(SourceFile:98)
	at eno.c(SourceFile:169)
	at bcn.execute(SourceFile:102)
	at eno.b(SourceFile:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:237)
	at enn.f(SourceFile:1244)
	at enn.e(SourceFile:802)
	at net.minecraft.client.main.Main.main(SourceFile:250)
Caused by: java.lang.RuntimeException: No key placement in MapLike[{"structures":[]}]
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101)
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93)
	at acl.a(SourceFile:176)
	... 30 more
13:38:31.297
eza
Render thread
Failed to validate datapack
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to load registries due to above errors
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:747)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at eza.a(SourceFile:630)
	at eza.a(SourceFile:590)
	at eza.a(SourceFile:562)
	at exu.c(SourceFile:56)
	at exv.aw_(SourceFile:77)
	at exv.a(SourceFile:108)
	at epi.c(SourceFile:94)
	at eoz.a(SourceFile:56)
	at epf.a(SourceFile:189)
	at eqs.a(SourceFile:38)
	at eno.b(SourceFile:98)
	at euq.a(SourceFile:409)
	at eno.a(SourceFile:98)
	at eno.c(SourceFile:169)
	at bcn.execute(SourceFile:102)
	at eno.b(SourceFile:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:237)
	at enn.f(SourceFile:1244)
	at enn.e(SourceFile:802)
	at net.minecraft.client.main.Main.main(SourceFile:250)
Caused by: java.lang.IllegalStateException: Failed to load registries due to above errors
	at acl.a(SourceFile:111)
	at adj.a(SourceFile:67)
	at adj.b(SourceFile:71)
	at adj.a(SourceFile:34)
	at eza.a(SourceFile:600)
	... 22 more
```
</details>

<details><summary>Settings on generator</summary>

![image](https://github.com/misode/misode.github.io/assets/45906780/7eb2a649-b404-4657-a775-9bebae99a9d9)
![image](https://github.com/misode/misode.github.io/assets/45906780/2b2d89b0-561b-4783-abad-c1c61b49c4ba)
![image](https://github.com/misode/misode.github.io/assets/45906780/b0c0884d-fddb-49cc-8917-5cd0d2e2c844)
![image](https://github.com/misode/misode.github.io/assets/45906780/15a637c3-37d2-46a4-adc8-10765a4027d5)
![image](https://github.com/misode/misode.github.io/assets/45906780/7a9321f2-d0a3-416b-a12d-4fcc77660710)

</details>

File that was generated: [customized.zip](https://github.com/misode/misode.github.io/files/11780051/customized.zip)

**Comment by misode** [comment]
Thank you for the report, this should now be fixed!
