### ISSUE TITLE
SyntaxError: Error importing: Unexpected token "

### ISSUE THREAD

**Issue by princessaylana** [misode/misode.github.io#426]
## Crash report
 * Page url: `https://misode.github.io/worldgen/feature/?version=1.20&preset=dark_forest_vegetation`
 * Generator ID: `worldgen/configured_feature`
 * Current version: `1.20`
 * Latest version: `23w40a`

### Stack trace
```
SyntaxError: Error importing: Unexpected token "
    at Ei (../../node_modules/comment-json/src/parse.js:87:16)
    at unexpected (../../node_modules/comment-json/src/parse.js:132:4)
    at expect (../../node_modules/comment-json/src/parse.js:251:6)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:337:28)
    at parse_array (../../node_modules/comment-json/src/parse.js:370:11)
    at walk (../../node_modules/comment-json/src/parse.js:283:32)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:283:32)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:random_selector",
  "config": {
    "features": [
      {
        "chance": 0.025,
        "feature": {
          "feature": "minecraft:huge_brown_mushroom",
          "placement": []
        }
      },
      {
        "chance": 0.05,
        "feature": {
          "feature": "minecraft:huge_red_mushroom",
          "placement": []
        }
      },
      {
        "chance": 0.6666667,
        "feature": "minecraft:dark_oak_checked"
      },
      {
        "chance": 0.2,
        "feature": "minecraft:birch_checked"
      },
      {
        "chance": 0.1,
        "feature": "minecraft:fancy_oak_checked"
      }
    ],
    "default": "minecraft:oak_checked"
  }
}
</pre>
</details>

**Comment by misode** [comment]
I have not enough information to find the issue. My guess is that you probably inserted invalid JSON.
