### ISSUE TITLE
New crossbow components not available in predicate

### ISSUE THREAD

**Issue by L-Lawlite** [misode/misode.github.io#491]
## Crash report
 * Page url: `https://misode.github.io/advancement/`
 * Generator ID: `advancement`
 * Current version: `1.20.5`
 * Latest version: `24w12a`

### Stack trace
```
SyntaxError: Error importing: Unexpected end of JSON input
    at yi (../../node_modules/comment-json/src/parse.js:94:16)
    at unexpected_end (../../node_modules/comment-json/src/parse.js:120:4)
    at type (../../node_modules/comment-json/src/parse.js:128:16)
    at is (../../node_modules/comment-json/src/parse.js:246:10)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:417:15)
    at parse (src/app/services/Source.ts:24:23)
    at async (src/app/services/Source.ts:43:8)
    at async (src/app/components/generator/SourcePanel.tsx:71:17)
```

### Generator JSON
<details>
<pre>
{
  "criteria": {
    "arrow": {
      "trigger": "minecraft:shot_crossbow",
      "conditions": {
        "item": {
          "predicates": {
            "minecraft:custom_data": "{EnchantmentPlusData:{Enchantments:[{id:\"enchantmentplus:amplified_shot\"}]}}",
            "minecraft:charged_projectiles": {}
          }
        }
      }
    }
  },
  "requirements": [
    [
      "arrow"
    ]
  ],
  "rewards": {
    "function": "enchantmentplus:test"
  }
}
</pre>
</details>

**Comment by misode** [comment]
`charged_projectiles` only exists as a data component, not as an item sub predicate
