### ISSUE TITLE
Crafting for version 1.12.2 in the mods build, what's wrong?

### ISSUE THREAD

**Issue by SayNooty** [misode/misode.github.io#512]
## Crash report
 * Page url: `https://misode.github.io/recipe/`
 * Generator ID: `recipe`
 * Current version: `1.15`
 * Latest version: `24w18a`

### Stack trace
```
SyntaxError: Error importing: Unexpected token "
    at Ei (../../node_modules/comment-json/src/parse.js:87:16)
    at unexpected (../../node_modules/comment-json/src/parse.js:132:4)
    at expect (../../node_modules/comment-json/src/parse.js:251:6)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:283:32)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:283:32)
    at parse_object (../../node_modules/comment-json/src/parse.js:365:11)
    at walk (../../node_modules/comment-json/src/parse.js:417:15)
    at parse (src/app/services/Source.ts:24:23)
```

### Generator JSON
<details>
<pre>
{
  "group": "ultimate_chest",
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "UNU",
    "NCN",
    "UNU"
  ],
  "key": {
    "N": {
      "item": "olderspark:netheriteblock"
    },
    "U": {
      "item": "industrialupgrade:upgrademodules"
      "data": 15
    },
    "C": {
      "item": "ironchest:iron_chest"
      "data": 6
    }
  },
  "result": {
    "item": "ultimatestorage:ultimate_chest",
    "count": 1
  }
}

</pre>
</details>

**Comment by misode** [comment]
Your JSON is invalid, you are missing a comma here:
![image](https://github.com/misode/misode.github.io/assets/17352009/129efde4-7d5a-474d-9f9f-ebafbb8dc764)

**Comment by SayNooty** [comment]
Thank you!
