### ISSUE TITLE
Error: Cannot display diff for this file

### ISSUE THREAD

**Issue by IllagerCaptain** [misode/misode.github.io#519]
## Crash report
 * Page url: `https://misode.github.io/versions/?id=24w20a&tab=diff&file=assets/minecraft/texts/credits.json`
 * Current version: `1.21`
 * Latest version: `24w20a`

### Stack trace
```
Error: Cannot display diff for this file
    at (https://misode.github.io/assets/index.66d99323.js:211:4780) (src/app/components/versions/VersionDiff.tsx:51:25)
    at n (../../node_modules/preact/hooks/dist/hooks.module.js:1:902)
    at useMemo (src/app/components/versions/VersionDiff.tsx:33:24)
    at wr.G4 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at uu (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
```

**Comment by misode** [comment]
The issue was caused because the GitHub API doesn't supply the patch data for large diffs. The implemented fix is to download the before and after files manually and use the `diff` package to create a patch file.

This diff can now be viewed: https://misode.github.io/versions/?id=24w20a&tab=diff&file=assets/minecraft/texts/credits.json
