### ISSUE TITLE
Error: Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:@

### ISSUE THREAD

**Issue by CapybaraIsSwagDev** [misode/misode.github.io#546]
## Crash report
 * Page url: `https://misode.github.io/recipe/`
 * Generator ID: `recipe`
 * Current version: `1.21`
 * Latest version: `1.21`

### Stack trace
```
Error: Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:@
    at new (../../node_modules/deepslate/lib/core/Identifier.js:13:18)
    at hr.parse (../../node_modules/deepslate/lib/core/Identifier.js:39:19)
    at parse (src/app/components/previews/RecipePreview.tsx:182:49)
    at placeItems (src/app/components/previews/RecipePreview.tsx:34:9)
    at n (../../node_modules/preact/hooks/dist/hooks.module.js:1:902)
    at useMemo (src/app/components/previews/RecipePreview.tsx:33:15)
    at wr.G4 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at uu (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    ""
  ],
  "key": {
    "#": {
      "item": "minecraft:stone"
    }
  },
  "result": {
    "id": "minecraft:@"
  }
}
</pre>
</details>

**Comment by Bread-NiceCat** [comment]
输出物品不能是minecraft:@"
