### ISSUE TITLE
Error: Error importing: Line 8: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by h0bbeSLOL** [misode/misode.github.io#571]
## Crash report
 * Page url: `https://misode.github.io/pack-mcmeta/`
 * Generator ID: `pack_mcmeta`
 * Current version: `1.21`
 * Latest version: `1.21`

### Stack trace
```
Error: Error importing: Line 8: Unexpected token ILLEGAL
    at p.constructError (../../node_modules/esprima/dist/esprima.js:5012:21)
    at p.createError (../../node_modules/esprima/dist/esprima.js:5028:26)
    at p.throwError (../../node_modules/esprima/dist/esprima.js:5035:20)
    at g.throwUnexpectedToken (../../node_modules/esprima/dist/esprima.js:5164:34)
    at g.scanPunctuator (../../node_modules/esprima/dist/esprima.js:5667:18)
    at g.lex (../../node_modules/esprima/dist/esprima.js:6264:21)
    at S.getNextToken (../../node_modules/esprima/dist/esprima.js:6675:83)
    at Object.h (../../node_modules/esprima/dist/esprima.js:154:35)
    at fi (../../node_modules/comment-json/src/parse.js:35:33)
    at tokenize (../../node_modules/comment-json/src/parse.js:402:11)
```

### Generator JSON
<details>
<pre>
{
  "pack": {
    "pack_format": 10,
    "description": "OP Loot from Birch Stairs"
  }
}
</pre>
</details>

**Comment by misode** [comment]
This was likely an error in the text you pasted when importing
