### ISSUE TITLE
SyntaxError: Something went wrong rendering the generator: Unexpected end of JSON input

### ISSUE THREAD

**Issue by melvinms** [misode/misode.github.io#597]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.21`
 * Latest version: `24w36a`

### Stack trace
```
SyntaxError: Something went wrong rendering the generator: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (src/app/components/ItemTooltip.tsx:118:34)
    at Array.map (<anonymous>)
    at map (src/app/components/ItemTooltip.tsx:117:18)
    at oi.e8 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at Oh (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:entity",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:netherite_sword",
          "functions": [
            {
              "function": "minecraft:set_components",
              "components": {
                "minecraft:lore": [
                  Uncommon
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
Your JSON is malformed, you need to quote the lore lines, like this:
```
"minecraft:lore": [
  "\"Uncommon\""
]
```

**Comment by melvinms** [comment]
Hello, how do I add custom color & format text ?TyLe 11 sept. 2024 à 16:54, Misode ***@***.***> a écrit :﻿
Your JSON is malformed, you need to quote the lore lines, like this:
"minecraft:lore": [
  "\"Uncommon\""
]

**Comment by misode** [comment]
If you use the `set_lore` function, the generator will help you with text component formatting. Unfortunately it does not work too well inside `set_components` because the JSON is nested
