### ISSUE TITLE
Unsupported project storage undefined

### ISSUE THREAD

**Issue by Kyberilium08** [misode/misode.github.io#637]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.21.2`
 * Latest version: `1.21.4-pre3`

### Stack trace
```
Error: Something went wrong rendering the generator: Something went wrong rendering the generator: Something went wrong rendering the generator: Unsupported project storage undefined
    at E3 (src/app/contexts/Project.tsx:172:7)
    at getProjectRoot (src/app/components/generator/ProjectPanel.tsx:25:21)
    at Vs.bS (../../node_modules/preact/dist/preact.module.js:1:8150)
    at u7 (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:6130)
    at j (../../node_modules/preact/dist/preact.module.js:1:1493)
```

**Comment by misode** [comment]
Thank you for reporting this! This only happened the first time when opening the site after the rewrite, and only when you had a non-default project open previously. It's been fixed so it should no longer happen for other users.
