### ISSUE TITLE
TypeError: Error creating share link: Failed to fetch

### ISSUE THREAD

**Issue by hunterkyou** [misode/misode.github.io#656]
## Crash report
 * Page url: `https://misode.github.io/item-modifier/`
 * Generator ID: `item_modifier`
 * Current version: `1.21.4`
 * Latest version: `1.21.4`

### Stack trace
```
TypeError: Error creating share link: Failed to fetch
TypeError: Error creating share link: Failed to fetch
    at Tk (https://misode.github.io/assets/index.f4214d99.js:235:29378)
    at yG (https://misode.github.io/assets/index.f4214d99.js:235:28943)
    at Object.be (https://misode.github.io/assets/index.f4214d99.js:373:4731)
    at HTMLDivElement.Bm (https://misode.github.io/assets/index.f4214d99.js:1:5633)
```

### Generator JSON
<details>
<pre>
{
  "apply_bonus": {}
}
</pre>
</details>

**Comment by misode** [comment]
When sharing a snippet, the website makes a request to an endpoint on https://snippets.misode.workers.dev. Maybe that domain is blocked in your country, or there was a brief Cloudflare issue? Does the issue still persist?

**Comment by hunterkyou** [comment]
我是孙志杰 我已经收到你的邮件。
